#! /bin/sh -x

# Make sure 'qemu-user-static' is installed.

set -e

manifest=ibmcloud-cli
image=quay.io/praiskup/ibmcloud-cli

#platform=linux/s390x
for platform in linux/amd64; do
    buildah build \
        --jobs=2 \
        --platform=$platform \
        --manifest=$manifest .
    buildah manifest push --all --format v2s2 "$manifest" "docker://$image"
done
