#! /bin/sh -ex

# Make sure 'qemu-user-static' is installed.

set -e

manifest=ibmcloud-cli
image=quay.io/praiskup/ibmcloud-cli

buildah bud \
    --layers \
    --jobs=2 \
    --platform=linux/amd64 \
    --platform=linux/s390x\
    --manifest=$manifest .

buildah manifest push --all --format v2s2 "$manifest" "docker://$image"
