#! /bin/bash -x

die() { echo >&2 "error: $*"; exit 1; }
base=copr-builder-image-s390x-$(date +"%Y%m%d-%H%M%S")
email=coprteam@fedoraproject.org
image=$(mount | cut -d' ' -f3 | grep qcow2| head -1)

test -n "$image" || die "no image mounted into container"

echo "Logging-in IBM CLoud, as $email"
echo "Uploading $image as $base"

# This requires the
# IBMCLOUD_API_KEY= exported
ibmcloud login -r jp-tok
uploaded_image=$base.qcow2

ibmcloud cos upload \
    --bucket fedora-images \
    --key "$uploaded_image" \
    --file "$image"

token=$(ibmcloud iam oauth-tokens | sed 's/.* //')

output=$(curl -X POST \
  "https://jp-tok.iaas.cloud.ibm.com/v1/images?version=2022-01-04&generation=2" \
  -H "Authorization: Bearer $token" \
  -H "Content-Type: application/json" \
  -H "accept: application/json" \
  -d '{
  "name": "'"$base"'",
  "operating_system": {
    "name": "fedora-server-34-s390x"
  },
  "file": {
    "href": "cos://jp-tok/fedora-images/'"$uploaded_image"'"
  },
  "resource_group": {
    "id": "803a282c432046c488b775f326ffc867"
  }
}')

image_id=$(echo "$output" | jq .id)
image_name=$(echo "$output" | jq .name)

echo "Uploaded image $image_id ($image_name)"
